version: '3.8'

services:
  master_postgres:
    container_name: some_postgres_container
    image: postgres:13.3
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  master_redis:
    image: redis:7
    ports:
      - "6379:6379"

  myapp:
    build: .
    container_name: url_shortener_container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://master_postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_REDIS_HOST: master_redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - master_postgres
      - master_redis

volumes:
  postgres_data:
