spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://master_postgres:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}

  data:
    redis:
      host: ${SPRING_REDIS_HOST:master_redis}
      port: ${SPRING_REDIS_PORT:6379}
      ttl-days: 1

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      queue_size: 100
      seq_batch_size: 110
      order_inserts: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

hashes:
  delete-scheduled:
    cron: "0 0 0 * * *"

logging:
  level:
    root: info

shortener:
  host: "http://localhost:8080/short-url/"
